// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/date-with-destiny/DateWithDestiny.tsx": () => import("../components/mockups/date-with-destiny/DateWithDestiny.tsx")
};
